apiVersion: apps/v1
kind: Deployment
metadata:
  name: asyncapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: async
  template:
    metadata:
      labels:
        app: async
    spec:
      containers:
      - name: async
        image: asyncapi:0.0.1
        resources:
          requests:
            memory: "512Mi"
            cpu: "1000m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: asyncservice
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: async