apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: echoapi:0.0.1
        resources:
          requests:
            memory: "512Mi"
            cpu: "2000m"
          limits:
            memory: "512Mi"
            cpu: "2000m"
        ports:
        - containerPort: 9595
---
apiVersion: v1
kind: Service
metadata:
  name: echoservice
spec:
  type: NodePort
  ports:
  - port: 9595
    targetPort: 9595
  selector:
    app: echo
