apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: syncservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: syncapi-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: asyncservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asyncapi-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80