apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sync
  template:
    metadata:
      labels:
        app: sync
    spec:
      containers:
      - name: sync
        image: syncapi:0.0.1
        resources:
          requests:
            memory: "512Mi"
            cpu: "1000m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: syncservice
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: sync